import type { DashboardData } from '@/types';

export const MOCK_DATA: DashboardData = {
  obras: [
    {
      idObra: 'OBR-001',
      cliente: 'Jairo e Ana',
      endereco: 'Rua das Palmeiras, 120 - Jardim Europa',
      responsavel: 'Carlos Mendes',
      arquiteto: 'Arq. Fernanda Lima',
      inicio: '2024-03-15',
      previsaoTermino: '2024-12-20',
      status: 'Em andamento',
      receitaPrevista: 450000,
      receitaRealizada: 280000,
      custoPrevisto: 320000,
      custoRealizado: 245000,
      lucroPrevisto: 130000,
      lucroRealizado: 35000,
    },
    {
      idObra: 'OBR-002',
      cliente: 'Roberto Silva',
      endereco: 'Av. Brasil, 890 - Centro',
      responsavel: 'Carlos Mendes',
      arquiteto: 'Arq. Paulo Tavares',
      inicio: '2024-06-01',
      previsaoTermino: '2025-03-30',
      status: 'Em andamento',
      receitaPrevista: 680000,
      receitaRealizada: 150000,
      custoPrevisto: 480000,
      custoRealizado: 120000,
      lucroPrevisto: 200000,
      lucroRealizado: 30000,
    },
  ],
  orcamentoMateriais: [
    { idObra: 'OBR-001', categoria: 'Revestimento', material: 'Porcelanato 60x60', unidade: 'm²', quantidade: 120, custoUnitario: 89.9, custoTotal: 10788, valorVenda: 13485 },
    { idObra: 'OBR-001', categoria: 'Revestimento', material: 'Argamassa AC-III', unidade: 'kg', quantidade: 600, custoUnitario: 2.5, custoTotal: 1500, valorVenda: 1875 },
    { idObra: 'OBR-001', categoria: 'Pintura', material: 'Tinta Acrílica Premium', unidade: 'lata', quantidade: 30, custoUnitario: 320, custoTotal: 9600, valorVenda: 12000 },
    { idObra: 'OBR-001', categoria: 'Elétrica', material: 'Cabo flexível 2,5mm', unidade: 'm', quantidade: 500, custoUnitario: 3.8, custoTotal: 1900, valorVenda: 2375 },
    { idObra: 'OBR-001', categoria: 'Hidráulica', material: 'Tubo PVC 50mm', unidade: 'm', quantidade: 80, custoUnitario: 12.5, custoTotal: 1000, valorVenda: 1250 },
    { idObra: 'OBR-001', categoria: 'Estrutura', material: 'Cimento CP-II', unidade: 'saco', quantidade: 200, custoUnitario: 38, custoTotal: 7600, valorVenda: 9500 },
    { idObra: 'OBR-002', categoria: 'Revestimento', material: 'Piso vinílico', unidade: 'm²', quantidade: 200, custoUnitario: 75, custoTotal: 15000, valorVenda: 18750 },
    { idObra: 'OBR-002', categoria: 'Pintura', material: 'Massa corrida', unidade: 'lata', quantidade: 40, custoUnitario: 55, custoTotal: 2200, valorVenda: 2750 },
  ],
  orcamentoServicos: [
    { idObra: 'OBR-001', ambiente: 'Sala', etapa: 'Acabamento', servico: 'Assentamento de piso', unidade: 'm²', quantidade: 45, custoUnitario: 65, custoTotal: 2925, valorVenda: 3656, status: 'Em andamento' },
    { idObra: 'OBR-001', ambiente: 'Cozinha', etapa: 'Acabamento', servico: 'Instalação de bancada', unidade: 'un', quantidade: 1, custoUnitario: 2800, custoTotal: 2800, valorVenda: 3500, status: 'Pendente' },
    { idObra: 'OBR-001', ambiente: 'Banheiro', etapa: 'Hidráulica', servico: 'Instalação de louças', unidade: 'un', quantidade: 5, custoUnitario: 180, custoTotal: 900, valorVenda: 1125, status: 'Concluído' },
    { idObra: 'OBR-001', ambiente: 'Quarto', etapa: 'Pintura', servico: 'Pintura latex PVA', unidade: 'm²', quantidade: 80, custoUnitario: 25, custoTotal: 2000, valorVenda: 2500, status: 'Pendente' },
    { idObra: 'OBR-001', ambiente: 'Fachada', etapa: 'Estrutura', servico: 'Reboco externo', unidade: 'm²', quantidade: 120, custoUnitario: 45, custoTotal: 5400, valorVenda: 6750, status: 'Concluído' },
    { idObra: 'OBR-002', ambiente: 'Hall', etapa: 'Acabamento', servico: 'Gesso acartonado', unidade: 'm²', quantidade: 60, custoUnitario: 85, custoTotal: 5100, valorVenda: 6375, status: 'Em andamento' },
  ],
  comprasReais: [
    { idObra: 'OBR-001', data: '2024-07-10', material: 'Porcelanato 60x60', fornecedor: 'Leroy Merlin', unidade: 'm²', quantidade: 50, valorUnitario: 92, valorTotal: 4600, centroCusto: 'Revestimento', status: 'Entregue' },
    { idObra: 'OBR-001', data: '2024-07-15', material: 'Tinta Acrílica Premium', fornecedor: 'Tintas MC', unidade: 'lata', quantidade: 15, valorUnitario: 335, valorTotal: 5025, centroCusto: 'Pintura', status: 'Entregue' },
    { idObra: 'OBR-001', data: '2024-07-22', material: 'Cimento CP-II', fornecedor: 'Depósito Central', unidade: 'saco', quantidade: 100, valorUnitario: 42, valorTotal: 4200, centroCusto: 'Estrutura', status: 'Entregue' },
    { idObra: 'OBR-001', data: '2024-08-01', material: 'Cabo flexível 2,5mm', fornecedor: 'Elétrica Brasil', unidade: 'm', quantidade: 300, valorUnitario: 4.2, valorTotal: 1260, centroCusto: 'Elétrica', status: 'Entregue' },
    { idObra: 'OBR-001', data: '2024-08-05', material: 'Argamassa AC-III', fornecedor: 'Leroy Merlin', unidade: 'kg', quantidade: 300, valorUnitario: 2.8, valorTotal: 840, centroCusto: 'Revestimento', status: 'Entregue' },
    { idObra: 'OBR-001', data: '2024-08-12', material: 'Tubo PVC 50mm', fornecedor: 'Hidráulica Express', unidade: 'm', quantidade: 40, valorUnitario: 14, valorTotal: 560, centroCusto: 'Hidráulica', status: 'Pendente' },
    { idObra: 'OBR-001', data: '2024-08-18', material: 'Porcelanato 60x60', fornecedor: 'Portobello Shop', unidade: 'm²', quantidade: 70, valorUnitario: 95, valorTotal: 6650, centroCusto: 'Revestimento', status: 'Entregue' },
    { idObra: 'OBR-001', data: '2024-09-02', material: 'Massa corrida', fornecedor: 'Tintas MC', unidade: 'lata', quantidade: 20, valorUnitario: 58, valorTotal: 1160, centroCusto: 'Pintura', status: 'Entregue' },
    { idObra: 'OBR-002', data: '2024-08-20', material: 'Piso vinílico', fornecedor: 'Duratex', unidade: 'm²', quantidade: 100, valorUnitario: 78, valorTotal: 7800, centroCusto: 'Revestimento', status: 'Entregue' },
    { idObra: 'OBR-002', data: '2024-09-01', material: 'Gesso acartonado', fornecedor: '', unidade: 'm²', quantidade: 30, valorUnitario: 42, valorTotal: 1260, centroCusto: '', status: 'Pendente' },
  ],
  maoDeObraReal: [
    { idObra: 'OBR-001', prestador: 'José Pedreiro', servico: 'Assentamento de piso', valorPrevisto: 2925, valorPago: 3200, extra: 275, dataExecucao: '2024-07-20', dataPagamento: '2024-08-05', status: 'Pago' },
    { idObra: 'OBR-001', prestador: 'Marcos Eletricista', servico: 'Instalação elétrica', valorPrevisto: 4500, valorPago: 4500, extra: 0, dataExecucao: '2024-08-10', dataPagamento: '2024-08-25', status: 'Pago' },
    { idObra: 'OBR-001', prestador: 'Silva Pinturas', servico: 'Pintura interna', valorPrevisto: 6000, valorPago: 0, extra: 0, dataExecucao: '', dataPagamento: '', status: 'Pendente' },
    { idObra: 'OBR-001', prestador: 'Carlos Encanador', servico: 'Instalação hidráulica', valorPrevisto: 3500, valorPago: 3800, extra: 300, dataExecucao: '2024-07-25', dataPagamento: '2024-08-10', status: 'Pago' },
    { idObra: 'OBR-002', prestador: 'Gesseiro Top', servico: 'Forro de gesso', valorPrevisto: 5100, valorPago: 2500, extra: 0, dataExecucao: '2024-09-01', dataPagamento: '', status: 'Em andamento' },
  ],
  medicoes: [
    { idObra: 'OBR-001', servico: 'Assentamento de piso', medicao: '1ª Medição', percentual: 60, valorMedido: 1755, status: 'Aprovada' },
    { idObra: 'OBR-001', servico: 'Assentamento de piso', medicao: '2ª Medição', percentual: 40, valorMedido: 1170, status: 'Pendente' },
    { idObra: 'OBR-001', servico: 'Reboco externo', medicao: '1ª Medição', percentual: 100, valorMedido: 5400, status: 'Aprovada' },
    { idObra: 'OBR-001', servico: 'Instalação de louças', medicao: '1ª Medição', percentual: 100, valorMedido: 900, status: 'Aprovada' },
    { idObra: 'OBR-001', servico: 'Pintura latex PVA', medicao: '1ª Medição', percentual: 0, valorMedido: 0, status: 'Não iniciada' },
    { idObra: 'OBR-002', servico: 'Gesso acartonado', medicao: '1ª Medição', percentual: 50, valorMedido: 2550, status: 'Em análise' },
  ],
  lastUpdated: new Date().toISOString(),
  connected: false,
  spreadsheetId: null,
  errors: [],
};
